# Generated by Django 4.0 on 2021-12-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
